### ISSUE TITLE
Storage selector encodes spaces special characters in subfolders incorrectly.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/component-storage-selector#33]
**How to recreate**
1. In the root Rise Vision company  add the Google Calendar Widget to a presentation
2. Select Custom Layout
3. Using the storage selector navigate to Acme Sign Co/AcmeKitchen2016/widget.html and select that file.

**What happens**
The link generated is [https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Acme%20Sign%20Co%2FAcmeKitchen2016%2Fwidget.html](https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Acme%20Sign%20Co%2FAcmeKitchen2016%2Fwidget.html)
this URL does not match the URL generated when "Generate URL" is selected in the Storage App.

**What should happen**
The link generated should match the same link generated by the Storage App itself, [https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Acme%20Sign%20Co/AcmeKitchen2016/widget.html](https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Acme%20Sign%20Co/AcmeKitchen2016/widget.html)

**Presentation**
https://goo.gl/wzWFcs

**Community Conversation**
[https://community.risevision.com/rise_vision_inc/topics/custom-layout-for-the-google-calendar-widget-stopped-working](https://community.risevision.com/rise_vision_inc/topics/custom-layout-for-the-google-calendar-widget-stopped-working)

**Comment by donnapep** [comment]
@btfrise I don't think this is logged in the correct repo. The component is not manipulating the URL in any way. It's just passing it through to the Widget directly based on what it gets back from https://apps.risevision.com/storage-selector.html. I think this may be one for the Apps team. Thx.

**Comment by alanclayton** [comment]
@alex-deaconu @ezequielc can you guys review this issue and confirm if it should go to you?

**Comment by alex-deaconu** [comment]
@alanclayton @donnapep @ezequielc this is a URL encoding issue. To clarify, the URL itself is not invalid, but the Widget uses relative references for its dependencies which cannot be found due to it being at the wrong path:
`https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/`
instead of 
`https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/Acme%20Sign%20Co/AcmeKitchen2016/`

However, "fixing" this by setting `/` instead of `%2F` may cause undesirable effects elsewhere. I'm not sure what the risk is, but there may have been an underlaying reason for the two generated URLs to differ.

Having said that, I'm not sure what the best course of action is here. Maybe we can try the suggested fix, and if anything breaks we can revert and re-evaluate. Thoughts? Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu Thanks. @rodrigopavezi @stulees @donnapep can you review and let me know your recommendation?

**Comment by donnapep** [comment]
@alanclayton @alex-deaconu I just checked and the `widget.html` file will load regardless of which version of the URL is used. It's the corresponding CSS and JS files referenced inside of `widget.html` that don't load.

@btfrise Can you clarify why you believe the URLs should match?

**Comment by btfrise** [comment]
@donnapep When the custom URL is selected through the storage selector, the custom layout does not appear. When the URL is generated through the Generate URL link in storage, the custom layout works.

**Comment by stulees** [comment]
@btfrise The difference in URL has no impact, that HTML file is always loaded. The real issue with this presentation is that the custom HTML being used is using relative paths to the widget css and JS source, which don't exist in the storage folder where the HTML resides - http://www.screencast.com/t/PpB2V3AmMHa . 

Change those paths in the HTML to be:

//s3.amazonaws.com/widget-google-calendar/0.1.0/dist/css/widget.min.css
//s3.amazonaws.com/widget-google-calendar/0.1.0/dist/js/widget.min.js
